### ISSUE TITLE
Error in makefile in test directory

### ISSUE THREAD

**Issue by Mousavikia** [vproc/vicuna#14] opened 2021-12-30 13:41 UTC
Hi I am working on Ibex and I want to attach vicuna as co processor to it... I managed to install rvv branch of gcc but when I run `make alu/vadd_8` I get this error below:
![Capture4](https://user-images.githubusercontent.com/96676046/147756802-b8bae388-1c07-45fd-8e57-5eedcf30f232.PNG)
How can I solve it?

Thank you in advance...

**Comment by michael-platzer** [comment] 2022-01-03 08:40
Which version of Verilator are you using? It seems like it does not support the -G option to override top-level parameter values.

**Comment by Mousavikia** [comment] 2022-01-03 10:37
Hi @michael-platzer  it's 3.874 and I installed it using `sudo apt-get install verilator` what version should I install?

**Comment by michael-platzer** [comment] 2022-01-03 11:11
That version has been released in 2015, please try to upgrade to a more recent version. Based on your screenshot I assume that you are using Ubuntu. [According to pkgs.org](https://pkgs.org/search/?q=verilator), all versions of Ubuntu that are still being supported have moved to more recent versions of Verilator.

The CI pipeline of this repository uses Verilator 4.028 and on my machine I currently use 4.200, which both work fine. Any version number in between should also work.

**Comment by Mousavikia** [comment] 2022-01-03 11:56
Thank you @michael-platzer ... As you mentioned in your earlier comment I upgraded my verilator to the newest version and it is working... I think I will ask more questions about your coprocessor since I have a masters thesis about CNN networks on RiscV processors with Vector extension... so thank you in advance if I ask more questions ahead...

**Comment by michael-platzer** [comment] 2022-01-04 10:24
Glad to hear that simulation works for you now. I am closing this issue, since the problem is resolved.

Please open a new issue if you encounter further problems or have other questions.

**Closed by michael-platzer** 2022-01-04 10:24 UTC
